version: '3.8'

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/meu_banco
    depends_on:
      - mongo
    networks:
      - rede-app

  # Serviço do banco de dados MongoDB
  mongo:
    image: mongo:latest
    container_name: mongodb_banco
    ports:
      - "27017:27017"
    volumes:
      - dados-mongo:/data/db
    networks:
      - rede-app

networks:
  rede-app:
    driver: bridge

volumes:
  dados-mongo: